---
name: Chris-WW
theme: jekyll-theme-slate
title: Chris Werner-Westoby
description: Systems, Information, Solutions - Using Mathematics and Technology to solve problems
email: ww.Chris@outlook.com
github_username: chris-ww
---