---
name: Chris-WW
theme: jekyll-theme-slate
title: Chris Werner-Westoby
description: Integrating Mathematics and Technology for smarter solutions
email: ww.Chris@outlook.com
github_username: chris-ww
---
